services:
  app:
    build: .
    environment:
      - MONGO_URL=mongodb://admin:password@mongo:27017/newDatabaseName
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
